name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ZekeSmith
          base: header, activity, community, repositories, metadata
          
          # Contributions calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          # Website Lighthouse benchmarks
          plugin_pagespeed: yes
          plugin_pagespeed_url: polymc.org
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          
          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
